spring:
  application:
    name: videomanagementservice

  cloud:
    aws:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      session-token: ${AWS_SESSION_TOKEN}
      region: us-east-1

dynamodb:
  table-name: ${DYNAMO_TABLE_NAME}
sqs:
  queue-url: ${SQS_QUEUE_URL}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
server:
  servlet:
    context-path: /video-management