spring:
  application:
    name: videomanagementservice

dynamodb:
  table-name: ${DYNAMO_TABLE_NAME}
sqs:
  notification:
    queue-url: ${SQS_NOTIFICATION_URL}
  video-uploaded:
    queue-url: ${SQS_VIDEO_UPLOADED_URL}
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
server:
  servlet:
    context-path: /video-management